version: '3.7'

services:
  main:
    container_name: main
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - 9229:9229
    command: npm run start:dev
    env_file:
      - .env
    environment:
      REDIS_HOST: redis
    networks:
      - webnet
    depends_on:
      - redis
  redis:
    container_name: redis
    image: redis:6
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - webnet
  mongo:
    container_name: mongo
    image: mongo:4.4
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db

volumes:
  mongo:

networks:
  webnet:
